# Generated by Django 3.0.8 on 2020-10-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20201019_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionimage',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionimage',
            name='survey',
        ),
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='survey.QuestionImage'),
        ),
    ]
