# Generated by Django 3.0.8 on 2020-10-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20201019_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\home\\Documents\\django-proj\\django-proj\\django-survey-master\\media/images'),
        ),
    ]
