# Generated by Django 3.0.8 on 2020-10-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20201019_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='survey.Question'),
        ),
    ]
